# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('WER_path', models.CharField(default=0, max_length=300)),
                ('Current_round', models.CharField(default=0, max_length=2)),
                ('Organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
