# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('currentOpp', models.CharField(default=0, max_length=75)),
                ('table', models.CharField(default=0, max_length=4)),
                ('name', models.CharField(max_length=75)),
                ('eventID', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
