# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0005_auto_20170530_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupfield',
            name='lookup_value_DCI',
        ),
        migrations.AddField(
            model_name='lookupfield',
            name='DCI_lookup',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lookupfield',
            name='Table_lookup',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
