# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0007_player_otable'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='current_round',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
