# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0008_document_current_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activePlayerID', models.CharField(max_length=10)),
                ('opponentID', models.CharField(max_length=10)),
                ('activePlayerWin', models.CharField(max_length=1)),
                ('opponentWin', models.CharField(max_length=1)),
                ('draws', models.CharField(max_length=2)),
                ('eventID', models.CharField(max_length=10)),
                ('roundNum', models.CharField(max_length=2)),
                ('tableNum', models.CharField(max_length=4)),
                ('byeCheck', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='Otable',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentOpp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='table',
        ),
    ]
