# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0009_auto_20170701_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='opponentName',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Otable',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
