# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0010_auto_20170701_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundUpdate', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='matches',
            name='activePlayerWin',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='matches',
            name='draws',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='matches',
            name='opponentWin',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
