# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0011_auto_20170702_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='activePlayerWin',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='matches',
            name='draws',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='matches',
            name='opponentWin',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
