# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepairings', '0012_auto_20170702_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='seatings',
            field=models.BooleanField(default=False),
        ),
    ]
